apiVersion: v1
kind: Service
metadata:
  name: dims-service
spec:
  ports:
    - port: 80
      targetPort: 3333
  selector:
    app: dims

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dims-deployment
spec:
  selector:
    matchLabels:
      app: dims
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dims
    spec:
      containers:
        - image: swensadocker/dims:1.0.0-dev-410
          name: dims
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
          env:
          - name: DB_HOST
            value: jdbc:mysql://mysql/dimsdb?useSSL=false
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            value: _GENERATE_PASSWORD_
          - name: AUTH_TYPE
            value: local
          ports:
            - containerPort: 3333
              name: dims
          volumeMounts:
            - name: ngnix-conf-location
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: ngnix-conf-location
          persistentVolumeClaim:
            claimName: nginx-pv-claim

